- options/base_options.py
- util/visualizer.py
Add options and functionalities for visdom port and display intermediate training results in single image pane.
Preview:
Visdom image caption/title doesn't support multi-line strings. Labels are displayed in a separate text pane so that they can be in the same ordered grid as the images.
> Visdom port and display intermediate in single image pane

- util/get_data.py
This class allows users to obtain the CycleGAN or Pix2Pix data from within Python (instead of using shell scripts).
Example:
```python
>>> from util.get_data import GetData
>>> gd = GetData(technique='cyclegan')
>>> new_data_path = gd.get(save_path='./datasets')
Options:
0: ae_photos.zip
1: apple2orange.zip
2: cezanne2photo.zip
3: cityscapes.zip
4: facades.zip
5: horse2zebra.zip
6: iphone2dslr_flower.zip
7: maps.zip
8: monet2photo.zip
9: ukiyoe2photo.zip
10: vangogh2photo.zip
Please enter the number of the dataset above you wish to download: 5
Downloading Data...
Unpacking Data...
```
> Add Tools to Easily Obtain CycleGAN or Pix2Pix Data

- models/networks.py
Since batch normalization already is trained for shift, conv bias parameters are not necessary. In case of instance normalization, one should still use bias but initialize to zero. Otherwise, default one initializes bias with uniform distribution between -stdv, +stdv [source](http://pytorch.org/docs/master/_modules/torch/nn/modules/conv.html#Conv1d)
> Bias initialization

- models/networks.py
To be consistent with Cyclegan(Torch), the latter half channels should receive the data from the skip connections.
> change the order of concanated channels

- util/image_pool.py
A tensor is now fed to ImagePool() instead of a Variable.
Sorry for the double PR, I was not able to put it in the same as the other one as I also have a private fork and therefore used the Github web interface to make the changes.
> gpu memory leaks

- models/base_model.py
- models/networks.py
Since the commit [Change device_id to device in python land #3133](https://github.com/pytorch/pytorch/pull/3133), keyword `device_id` has been changed to `device`
> Compatible with the latest version.

- models/base_model.py
- models/cycle_gan_model.py
- models/networks.py
- models/pix2pix_model.py
- models/test_model.py
1. Remove kwargs of `.cuda` so that the code is compatible with both old and new PyTorch version.
2. Change `.forward` on modules to `__call__`.
cc @soumith
> PyTorch best practices

- data/custom_dataset_data_loader.py
Current `max_dataset_size` has no use except printing because `BaseDataLoader.__len__` isn't really used in training/testing. This PR fixes the option.
> Fix max_dataset_size

- README.md
As the commit message, "You can test your model on your training set by setting ``phase='train'`` in  `test.lua`." is an old description for lua project.
> fix typos at command options in readme

- data/aligned_dataset.py
This is important to train the generator with input images that are normalized without the truth such that when the model is used in test time and the truth is not available, the input will be normalized similarly as during training.
> Should normalize input and truth images separately

- models/base_model.py
After some work of understanding your nice model implementation, I just wanted to start my contribution by removing this unneeded assignment as the attribute `self.input` is never used.  
First of all, thank you a lot for open-sourcing your model implementation. If every scientific author did that the world would be a better place.
However, I have a small request. When you and other parties make further developing on this codebase, would you please enforce the use of docstrings, for instance, [numpydoc docstring](https://docs.scipy.org/doc/numpy-1.15.0/docs/howto_document.html). That would make it much easier for new parties, like my self, to understand the code, such that we all can fix potential bugs and expand the codebase.
Regards Peter Fogh
> Removed unneeded `self.input` attribute

- docs/qa.md
The way to run in cpu mode is with --gpu_ids -1. Likely it was changed at some point and the docs need to be updated to reflect that change. --device_ids -1 isn't accepted as a commanline argument to python train.py.
Apologies if the --device_ids -1 is a correct commandline argument to a different .py file!
> Fix incorrect commandline argument

- README.md
Failure to run `python -m visdom.server` before you train a model will result in errors. Suggest adding this as a step before `python train.py...` in readme.
> change order for training a model

- options/train_options.py
`SyntaxError: Non-ASCII character '\xef' in file /data/pytorch-CycleGAN-and-pix2pix/options/train_options.py on line 34, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details`
encountered this error when going through the steps to get started. Just a minor fix
> remove Non-ASCII character '\xef'

- options/base_options.py
I think it is usefull to save training and test options in different files. Now we rewrite training options when we run test script. And after that it is hard to restore all training options.
> separate save train and test options

- docs/qa.md
These files I corrected were changed since the commit 568ad02a.
To avoid obsoletion and misleading, it might be a good idea to change linked URLs from `master` to specific commit.
Like `https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix/tree/22fe4465c120ac92a2de09c3c2d50cbbe0e63f29/data/aligned_dataset.py#L41`
> Update q and a

- README.md
Google Colab for pix2pix previously linked to the CycleGan. Fixed it.
> Fixed pix2pix Google Colab and Code links

- data/aligned_dataset.py
- data/colorization_dataset.py
- data/image_folder.py
- data/unaligned_dataset.py
Importing both `os` and `os.path` is redundant since importing `os` will import `os.path` and importing `os.path` will also import the `os` package. So it's more clean and explicit to simply `import os` because that reflects better on what the import is actually doing.
Reference: https://www.mail-archive.com/python-list@python.org/msg188236.html
> Changing import os.path to import os

- environment.yml
Prevents getting spammed with a wall of `Warning: you have pip-installed dependencies in your environment file, but you do not list pip itself as one of your conda dependencies.  Conda may not use the correct pip to install your packages, and they may end up in the wrong place.  Please add an explicit pip dependency.  I'm adding one for you, but still nagging you.
` .
> conda no longer comes with pip, need to install it explicitly

- CycleGAN.ipynb
- datasets/prepare_cityscapes_dataset.py
- scripts/eval_cityscapes/evaluate.py
- correct download dataset list in CycleGAN.ipynb
- typo of gtFine_dir in example usage in cityscapes evaluation
- scipy.misc.imresize is deprecated in cityscapes evaluation
> minor mistakes/typos

- data/base_dataset.py
The original code will frequently output an annoying warning message: `UserWarning: Argument interpolation should be of type InterpolationMode instead of int. Please, use InterpolationMode enum. `
> change image.bicubic to transformer bicubic to avoid output warning
