junyanz/pytorch-CycleGAN-and-pix2pix

data/base_dataset.py, data/single_dataset.py, data/unaligned_dataset.py, options/base_options.py, util/visualizer.py
+ Changed resize_or_crop code so that its behavior now matches the description.
+ Added scale_width_and_crop value for resize_or_crop option.
+ Improved single image display to using <style/> and to align text at center.
+ Fixed previous type in single image display.
=> Improve resize_or_crop option and single image display

models/cycle_gan_model.py
The memory leak happened only with the new version of Pytorch and Cuda 9.0. I did not have this problem before.
=> gpu memory leaks

models/cycle_gan_model.py
fixes CycleGan ```get_current_visuals```
=> util.tensor2im takes data, not Variable

models/cycle_gan_model.py, models/pix2pix_model.py, models/test_model.py
=> Fix resize_ issue #170

.gitignore, environment.yml, make_dataset_aligned.py, train.py
When trying to run this on Windows, I got an exception like this:
https://github.com/KupynOrest/DeblurGAN/issues/22
I applied a fix like this to make it work:
https://medium.com/@mackie__m/running-a-cifar-10-image-classifier-on-windows-with-pytorch-9094e29089cd#869f
=> Fix multiprocessing for Windows by using if __name__ == '__main__'

README.md, models/base_model.py, models/cycle_gan_model.py, models/networks.py, models/pix2pix_model.py, models/test_model.py, requirements.txt, util/image_pool.py, util/util.py, util/visualizer.py
I've manually verified that training pix2pix & CycleGAN, and testing pretrained models of pix2pix & CycleGAN work.
=> PyTorch 0.4 compatibility

data/__init__.py
There's an error in the description string of the helper function `find_dataset_using_name`.
=> Fix the error doc string in the data init helper function

README.md
Fixed inlogicality in installation instrutions.
=> Moved instruction for deps installation after cloning repo

docs/qa.md
Missing closing parenthesis on print statement
=> Fix syntax error

datasets/download_cyclegan_dataset.sh
"ae_photos" was duplicated, delete it.
=> datasets_downloeder was duplicated, delete it.

models/__init__.py
I believe the comments of the two lines should be swapped.
=> update misplaced comment

models/networks.py
I know currently cycleGAN does not use wgan-gp, though for completeness, I think this should speed up things a bit if someone is using this option.
=> Create random wgangp alpha directly on device

CycleGAN.ipynb, Pix2Pix.ipynb, README.md
Hi,
I added two colab notebooks that show how to use CycleGAN and Pix2Pix. I also added two "Open In Colab" badges to the README that will open up the jupyter notebooks in colab once the pull request has been merged in. You can take a look at the notebooks [here](https://github.com/bkkaggle/pytorch-CycleGAN-and-pix2pix/blob/master/CycleGAN.ipynb) and [here](https://github.com/bkkaggle/pytorch-CycleGAN-and-pix2pix/blob/master/Pix2Pix.ipynb)
=> Colab quickstarts for CycleGAN and Pix2Pix

translate/spanish/README.md
This translation was written carefully and verified by a Spanish speaker.
=> Readme Spanish Translate

docs/README_es.md
=> Broken links and minimal grammar fixed.

datasets/combine_A_and_B.py
Good afternoon! I parallelized the image writing portion of the combine_A_and_B script in /datasets. This version takes advantage of multiple CPUs and runs much faster.
=> Parallelized combine_A_and_B script

docs/qa.md
In line25, it should be ‘installed’ instead of 'installl' :)
=> Correct a spelling mistake

test.py, util/visualizer.py
This PR improves the label from the previous PR https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix/pull/1317
=> Minor naming fix 

.gitignore, environment.yml, models/networks.py, options/base_options.py, scripts/edges/batch_hed.py, scripts/eval_cityscapes/evaluate.py, test.py, util/visualizer.py
- Added support to have a custom `wandb` project name.
- Added `wandb` in environment.yml file as pip package.
- Added `wandb` log directory into `gitignore`
- Fixed `flake8` code enforcements rules.
=> Added option to read wandb-project-name as a command line argument 

docs/qa.md
Thought this would be a common question, so adding to the FAQ.
=> Added QnA about loading the saved model

models/pix2pix_model.py
=> fix typo in pix2pix_model.py
